#2021 amanda & MathMan, updated 08/march/2021 14:08 PM
AMANDA_FLAGS__=-O3 -Wall -Wfatal-errors -Werror -Wno-unused-function -Wno-unused-but-set-variable

amanda_32: /bw_tmp/compress2/pedro_32arp.o /bw_tmp/compress2/arp_dll_32arp.o /bw_tmp/compress2/compress2_z_32.o /bw_tmp/compress2/compress2_2_z_32.o /bw_tmp/compress2/compress2dll_32.o /bw_tmp/compress2/longfile_32arp.o /bw_tmp/compress2/compress42_thread_1_32.o /bw_tmp/compress2/compress42_thread_2_32.o /bw_tmp/compress2/compress42_thread_3_32.o /bw_tmp/compress2/compress42_thread_4_32.o /bw_tmp/compress2/compress42_thread_5_32.o /bw_tmp/compress2/compress42_thread_6_32.o /bw_tmp/compress2/compress42_thread_7_32.o /bw_tmp/compress2/stdio_v2_32arp.o /bw_tmp/compress2/compress42_32.o

#	-rm *.DLL *.dll *.ric *~ *.exe *.EXE *.o

	(/bw_tmp/amandaricardo_mvbuild26_33.exe amanda_file_counter_32.ini versio_n.ama.rc version_ricardo_mislaine_final_2_.rc aline_definitive_header_2_.h "31.5 bits ;-)" BE_compress2_aakp_32.DLL increase &&   i686-w64-mingw32-windres.exe -o /bw_tmp/compress2/version_x86.o -O coff version_ricardo_mislaine_final_2_.rc)

	@i686-w64-mingw32-gcc -O3 -o /bin/tar/x86/BE_compress2_aakp_32.DLL -shared arp.def /bw_tmp/compress2/version_x86.o /bw_tmp/compress2/pedro_32arp.o /bw_tmp/compress2/arp_dll_32arp.o /bw_tmp/compress2/compress2_z_32.o /bw_tmp/compress2/compress2_2_z_32.o /bw_tmp/compress2/compress2dll_32.o /bw_tmp/compress2/longfile_32arp.o /bw_tmp/compress2/compress42_thread_1_32.o /bw_tmp/compress2/compress42_thread_2_32.o /bw_tmp/compress2/compress42_thread_3_32.o /bw_tmp/compress2/compress42_thread_4_32.o /bw_tmp/compress2/compress42_thread_5_32.o /bw_tmp/compress2/compress42_thread_6_32.o /bw_tmp/compress2/compress42_thread_7_32.o /bw_tmp/compress2/stdio_v2_32arp.o /bw_tmp/compress2/compress42_32.o -Wl,-enable-stdcall-fixup -static-libgcc

/bw_tmp/compress2/compress42_32.o : c/tools/compress42.c c/tools/decompress_for_all_z.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/compress42_32.o c/tools/compress42.c $(AMANDA_FLAGS__)

/bw_tmp/compress2/compress42_thread_1_32.o : c/tools/compress42_thread_1.c c/tools/decompress_for_all_z.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/compress42_thread_1_32.o c/tools/compress42_thread_1.c $(AMANDA_FLAGS__)

/bw_tmp/compress2/compress42_thread_2_32.o : c/tools/compress42_thread_2.c c/tools/decompress_for_all_z.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/compress42_thread_2_32.o c/tools/compress42_thread_2.c $(AMANDA_FLAGS__)

/bw_tmp/compress2/compress42_thread_3_32.o : c/tools/compress42_thread_3.c c/tools/decompress_for_all_z.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/compress42_thread_3_32.o c/tools/compress42_thread_3.c $(AMANDA_FLAGS__)

/bw_tmp/compress2/compress42_thread_4_32.o : c/tools/compress42_thread_4.c c/tools/decompress_for_all_z.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/compress42_thread_4_32.o c/tools/compress42_thread_4.c $(AMANDA_FLAGS__)

/bw_tmp/compress2/compress42_thread_5_32.o : c/tools/compress42_thread_5.c c/tools/decompress_for_all_z.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/compress42_thread_5_32.o c/tools/compress42_thread_5.c $(AMANDA_FLAGS__)

/bw_tmp/compress2/compress42_thread_6_32.o : c/tools/compress42_thread_6.c c/tools/decompress_for_all_z.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/compress42_thread_6_32.o c/tools/compress42_thread_6.c $(AMANDA_FLAGS__)

/bw_tmp/compress2/compress42_thread_7_32.o : c/tools/compress42_thread_7.c c/tools/decompress_for_all_z.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/compress42_thread_7_32.o c/tools/compress42_thread_7.c $(AMANDA_FLAGS__)

/bw_tmp/compress2/longfile_32arp.o : c/tools/longfile.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/longfile_32arp.o c/tools/longfile.c $(AMANDA_FLAGS__)

/bw_tmp/compress2/stdio_v2_32arp.o : c/tools/stdio_v2.c c/tools/stdio_v2.h c/tools/stdio_v3.h
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/stdio_v2_32arp.o c/tools/stdio_v2.c $(AMANDA_FLAGS__)

/bw_tmp/compress2/pedro_32arp.o: pedro.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/pedro_32arp.o pedro.c $(AMANDA_FLAGS__)

/bw_tmp/compress2/arp_dll_32arp.o : c/tools/helper_utilities_by_amanda_and_ricardo.c c/tools/arp_dll.c c/tools/stdio_v2.h c/tools/stdio_v3.h
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/arp_dll_32arp.o c/tools/arp_dll.c $(AMANDA_FLAGS__)

/bw_tmp/compress2/compress2_z_32.o : c/tools/compress2_z.c c/tools/stdio_v2.h c/tools/stdio_v3.h
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/compress2_z_32.o c/tools/compress2_z.c $(AMANDA_FLAGS__)

/bw_tmp/compress2/compress2_2_z_32.o : c/tools/compress2_2_z.c c/tools/lzop2_multi.c c/tools/lzop2_thread.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/compress2_2_z_32.o c/tools/compress2_2_z.c $(AMANDA_FLAGS__)

/bw_tmp/compress2/compress2dll_32.o : c/tools/compress2dll.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/compress2dll_32.o c/tools/compress2dll.c $(AMANDA_FLAGS__)

################################64 bits

ricardo_64: /bw_tmp/compress2/pedro_64arp.o /bw_tmp/compress2/arp_dll_64arp.o /bw_tmp/compress2/compress2_z_64.o /bw_tmp/compress2/compress2_2_z_64.o /bw_tmp/compress2/compress2dll_64.o /bw_tmp/compress2/longfile_64arp.o /bw_tmp/compress2/compress42_thread_1_64.o /bw_tmp/compress2/compress42_thread_2_64.o /bw_tmp/compress2/compress42_thread_3_64.o /bw_tmp/compress2/compress42_thread_4_64.o /bw_tmp/compress2/compress42_thread_5_64.o /bw_tmp/compress2/compress42_thread_6_64.o /bw_tmp/compress2/compress42_thread_7_64.o /bw_tmp/compress2/stdio_v2_64arp.o /bw_tmp/compress2/compress42_64.o
	
	(/bw_tmp/amandaricardo_mvbuild26_33.exe amanda_file_counter_32.ini versio_n.ama.rc version_ricardo_mislaine_final_2_.rc aline_definitive_header_2_.h "63.5 bits ;-)" BE_compress2_aakp_64.DLL increase && x86_64-w64-mingw32-windres.exe -o /bw_tmp/compress2/version_x64.o -O coff version_ricardo_mislaine_final_2_.rc)

	@x86_64-w64-mingw32-gcc.exe -O3 -o /bin/tar/x64/BE_compress2_aakp_64.DLL -shared arp.def /bw_tmp/compress2/version_x64.o /bw_tmp/compress2/pedro_64arp.o /bw_tmp/compress2/arp_dll_64arp.o /bw_tmp/compress2/compress2_z_64.o /bw_tmp/compress2/compress2_2_z_64.o /bw_tmp/compress2/compress2dll_64.o /bw_tmp/compress2/longfile_64arp.o /bw_tmp/compress2/compress42_thread_1_64.o /bw_tmp/compress2/compress42_thread_2_64.o /bw_tmp/compress2/compress42_thread_3_64.o /bw_tmp/compress2/compress42_thread_4_64.o /bw_tmp/compress2/compress42_thread_5_64.o /bw_tmp/compress2/compress42_thread_6_64.o /bw_tmp/compress2/compress42_thread_7_64.o /bw_tmp/compress2/stdio_v2_64arp.o /bw_tmp/compress2/compress42_64.o	-Wl,-enable-stdcall-fixup -static-libgcc

/bw_tmp/compress2/compress42_64.o : c/tools/compress42.c c/tools/decompress_for_all_z.c
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/compress42_64.o c/tools/compress42.c $(AMANDA_FLAGS__)

/bw_tmp/compress2/compress42_thread_1_64.o : c/tools/compress42_thread_1.c c/tools/decompress_for_all_z.c
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/compress42_thread_1_64.o c/tools/compress42_thread_1.c $(AMANDA_FLAGS__)

/bw_tmp/compress2/compress42_thread_2_64.o : c/tools/compress42_thread_2.c c/tools/decompress_for_all_z.c
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/compress42_thread_2_64.o c/tools/compress42_thread_2.c $(AMANDA_FLAGS__)

/bw_tmp/compress2/compress42_thread_3_64.o : c/tools/compress42_thread_3.c c/tools/decompress_for_all_z.c
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/compress42_thread_3_64.o c/tools/compress42_thread_3.c $(AMANDA_FLAGS__)

/bw_tmp/compress2/compress42_thread_4_64.o : c/tools/compress42_thread_4.c c/tools/decompress_for_all_z.c
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/compress42_thread_4_64.o c/tools/compress42_thread_4.c $(AMANDA_FLAGS__)

/bw_tmp/compress2/compress42_thread_5_64.o : c/tools/compress42_thread_5.c c/tools/decompress_for_all_z.c
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/compress42_thread_5_64.o c/tools/compress42_thread_5.c $(AMANDA_FLAGS__)

/bw_tmp/compress2/compress42_thread_6_64.o : c/tools/compress42_thread_6.c c/tools/decompress_for_all_z.c
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/compress42_thread_6_64.o c/tools/compress42_thread_6.c $(AMANDA_FLAGS__)

/bw_tmp/compress2/compress42_thread_7_64.o : c/tools/compress42_thread_7.c c/tools/decompress_for_all_z.c
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/compress42_thread_7_64.o c/tools/compress42_thread_7.c $(AMANDA_FLAGS__)

/bw_tmp/compress2/longfile_64arp.o : c/tools/longfile.c
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/longfile_64arp.o c/tools/longfile.c $(AMANDA_FLAGS__)

/bw_tmp/compress2/stdio_v2_64arp.o : c/tools/stdio_v2.c c/tools/stdio_v2.h c/tools/stdio_v3.h
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/stdio_v2_64arp.o  c/tools/stdio_v2.c $(AMANDA_FLAGS__)

/bw_tmp/compress2/pedro_64arp.o: pedro.c
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/pedro_64arp.o pedro.c $(AMANDA_FLAGS__)

/bw_tmp/compress2/arp_dll_64arp.o : c/tools/helper_utilities_by_amanda_and_ricardo.c c/tools/arp_dll.c c/tools/stdio_v2.h c/tools/stdio_v3.h
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/arp_dll_64arp.o c/tools/arp_dll.c $(AMANDA_FLAGS__)

/bw_tmp/compress2/compress2_z_64.o : c/tools/compress2_z.c c/tools/stdio_v2.h  c/tools/stdio_v3.h
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/compress2_z_64.o c/tools/compress2_z.c $(AMANDA_FLAGS__)

/bw_tmp/compress2/compress2_2_z_64.o : c/tools/compress2_2_z.c c/tools/lzop2_multi.c c/tools/lzop2_thread.c
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/compress2_2_z_64.o c/tools/compress2_2_z.c $(AMANDA_FLAGS__)

/bw_tmp/compress2/compress2dll_64.o : c/tools/compress2dll.c
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/compress2/compress2dll_64.o c/tools/compress2dll.c $(AMANDA_FLAGS__)
