#december 2020 amanda & ricardo

AMANDA_FLAGS__=-O3 -Wall -Wfatal-errors -Werror -Wno-unused-function

amanda_32: /bw_tmp/compress/compress_32aakp.o /bw_tmp/compress/pedro_32aakp.o

	-rm *~ *.DLL *.dll *.o *.exe *.EXE

	(/bw_tmp/amandaricardo_mvbuild26_33.exe amanda_file_counter_32.ini versio_n.ama.rc version_ricardo_mislaine_final_2_.rc aline_definitive_header_2_.h "31.5 bits ;-)" BE_compress_aakp_32.DLL increase &&   i686-w64-mingw32-windres.exe -o /bw_tmp/compress/version_x86.o -O coff version_ricardo_mislaine_final_2_.rc)

	@i686-w64-mingw32-gcc.exe $(AMANDA_FLAGS__)	-shared -o /bin/tar/x86/BE_compress_aakp_32.DLL AAKP.def /bw_tmp/compress/version_x86.o /bw_tmp/compress/compress_32aakp.o /bw_tmp/compress/pedro_32aakp.o -Wl,-enable-stdcall-fixup -static-libgcc

/bw_tmp/compress/compress_32aakp.o: helper_utilities_by_amanda_and_ricardo.c compress42.c

	@i686-w64-mingw32-gcc.exe -c -o /bw_tmp/compress/compress_32aakp.o compress42.c $(AMANDA_FLAGS__)

/bw_tmp/compress/pedro_32aakp.o: pedro.c

	@i686-w64-mingw32-gcc.exe -c -o /bw_tmp/compress/pedro_32aakp.o pedro.c $(AMANDA_FLAGS__)

ricardo_64: /bw_tmp/compress/compress_64aakp.o /bw_tmp/compress/pedro_64aakp.o

	(/bw_tmp/amandaricardo_mvbuild26_33.exe amanda_file_counter_32.ini versio_n.ama.rc version_ricardo_mislaine_final_2_.rc aline_definitive_header_2_.h "63.5 bits ;-)" BE_compress_aakp_64.DLL increase && x86_64-w64-mingw32-windres.exe -o /bw_tmp/compress/version_x64.o -O coff version_ricardo_mislaine_final_2_.rc)

	@x86_64-w64-mingw32-gcc -O3 -shared -o /bin/tar/x64/BE_compress_aakp_64.DLL AAKP.def /bw_tmp/compress/version_x64.o	/bw_tmp/compress/compress_64aakp.o /bw_tmp/compress/pedro_64aakp.o -Wl,-enable-stdcall-fixup   \
	-static-libgcc

/bw_tmp/compress/compress_64aakp.o  : helper_utilities_by_amanda_and_ricardo.c compress42.c

	@x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/compress/compress_64aakp.o compress42.c $(AMANDA_FLAGS__)

/bw_tmp/compress/pedro_64aakp.o: pedro.c

	@x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/compress/pedro_64aakp.o pedro.c $(AMANDA_FLAGS__)
