/* Generated by automated build script */
#define SNAPSHOT
#define TEXTVER "Development snapshot 2021-02-03.b63a66c"
#define SSHVER "-Snapshot-2021-02-03.b63a66c"
#define BINARY_VERSION 0,74,1228,0
#define SOURCE_COMMIT "b63a66cd2c96a0e44af96a03adb3081a9d93ecb3"
