#2021 amanda & MathMan, updated 08/march/2021 14:08 PM
AMANDA_FLAGS__=-O3 -Wall -Wfatal-errors -Werror
FELINE_FLAGS__=-Wno-unused-function -Wno-unused-but-set-variable
JULIET_FLAGS  =

amanda_32: amandaricardo_koci_dprintf_32arp.o    \
	arp_dll_32arp.o compress2_z_32.o             \
	compress2_2_z_32.o compress2dll_32.o         \
	longfile_32arp.o compress42_thread_1_32.o    \
	compress42_thread_2_32.o                     \
	compress42_thread_3_32.o                     \
	compress42_thread_4_32.o                     \
	compress42_thread_5_32.o                     \
	compress42_thread_6_32.o                     \
	compress42_thread_7_32.o                     \
	stdio_v2_32arp.o compress42_32.o
	
	i686-w64-mingw32-gcc -O3 -o                  \
	BE_compress2_aakp_32.DLL -mdll               \
	arp.def                                      \
	amandaricardo_koci_dprintf_32arp.o           \
	arp_dll_32arp.o compress2_z_32.o             \
	compress2_2_z_32.o compress2dll_32.o         \
	longfile_32arp.o compress42_thread_1_32.o    \
	compress42_thread_2_32.o                     \
	compress42_thread_3_32.o                     \
	compress42_thread_4_32.o                     \
	compress42_thread_5_32.o                     \
	compress42_thread_6_32.o                     \
	compress42_thread_7_32.o                     \
	stdio_v2_32arp.o compress42_32.o             \
	-Wl,-enable-stdcall-fixup

	@cp BE_compress2_aakp_32.DLL ../../
	@cp BE_compress2_aakp_32.DLL  'C:\Amanda Ava Pereira\nosso_trabalho\amanda_projects\Lurdes_tar_gzip_parolin_k\files_k\tar_sample_ar\tar_sample_ar\bin\Release\'
	
	@./espaco_arp.exe 83
	

compress42_32.o :                                \
	c/tools/compress42.c
	i686-w64-mingw32-gcc.exe -c -o               \
	compress42_32.o                              \
	c/tools/compress42.c                         \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83
	
compress42_thread_1_32.o :                       \
	c/tools/compress42_thread_1.c
	i686-w64-mingw32-gcc.exe -c -o               \
	compress42_thread_1_32.o                     \
	c/tools/compress42_thread_1.c                \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83
	
compress42_thread_2_32.o :                       \
	c/tools/compress42_thread_2.c
	i686-w64-mingw32-gcc.exe -c -o               \
	compress42_thread_2_32.o                     \
	c/tools/compress42_thread_2.c                \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83
	
compress42_thread_3_32.o :                       \
	c/tools/compress42_thread_3.c
	i686-w64-mingw32-gcc.exe -c -o               \
	compress42_thread_3_32.o                     \
	c/tools/compress42_thread_3.c                \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83
	
compress42_thread_4_32.o :                       \
	c/tools/compress42_thread_4.c
	i686-w64-mingw32-gcc.exe -c -o               \
	compress42_thread_4_32.o                     \
	c/tools/compress42_thread_4.c                \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83
	
compress42_thread_5_32.o :                       \
	c/tools/compress42_thread_5.c
	i686-w64-mingw32-gcc.exe -c -o               \
	compress42_thread_5_32.o                     \
	c/tools/compress42_thread_5.c                \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83
	
compress42_thread_6_32.o :                       \
	c/tools/compress42_thread_6.c
	i686-w64-mingw32-gcc.exe -c -o               \
	compress42_thread_6_32.o                     \
	c/tools/compress42_thread_6.c                \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83
	
compress42_thread_7_32.o :                       \
	c/tools/compress42_thread_7.c
	i686-w64-mingw32-gcc.exe -c -o               \
	compress42_thread_7_32.o                     \
	c/tools/compress42_thread_7.c                \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83
	
longfile_32arp.o :                               \
	c/tools/longfile.c
	i686-w64-mingw32-gcc.exe -c -o               \
	longfile_32arp.o                             \
	c/tools/longfile.c                           \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83
	
stdio_v2_32arp.o :                               \
	c/tools/stdio_v2.c                           \
	c/tools/stdio_v2.h c/tools/stdio_v3.h
	i686-w64-mingw32-gcc.exe -c -o               \
	stdio_v2_32arp.o                             \
	c/tools/stdio_v2.c                           \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83
	
amandaricardo_koci_dprintf_32arp.o :             \
	c/tools/amandaricardo_koci_dprintf.c
	i686-w64-mingw32-gcc.exe -c -o               \
	amandaricardo_koci_dprintf_32arp.o           \
	c/tools/amandaricardo_koci_dprintf.c         \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83
	
arp_dll_32arp.o :                                \
	c/tools/helper_utilities_by_amanda_and_ricardo.c \
	c/tools/arp_dll.c c/tools/stdio_v2.h         \
	c/tools/stdio_v3.h
	i686-w64-mingw32-gcc.exe -c -o               \
	arp_dll_32arp.o c/tools/arp_dll.c            \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83
	
compress2_z_32.o :   c/tools/compress2_z.c       \
	c/tools/stdio_v2.h  c/tools/stdio_v3.h
	i686-w64-mingw32-gcc.exe -c -o               \
	compress2_z_32.o c/tools/compress2_z.c       \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83
#	unc77.bat c/tools/brotli.c

compress2_2_z_32.o :   c/tools/compress2_2_z.c
	i686-w64-mingw32-gcc.exe -c -o               \
	compress2_2_z_32.o c/tools/compress2_2_z.c   \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83

compress2dll_32.o :   c/tools/compress2dll.c
	i686-w64-mingw32-gcc.exe -c -o               \
	compress2dll_32.o c/tools/compress2dll.c     \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83

################################64 bits

ricardo_64: amandaricardo_koci_dprintf_64arp.o   \
	arp_dll_64arp.o compress2_z_64.o             \
	compress2_2_z_64.o compress2dll_64.o         \
	longfile_64arp.o compress42_thread_1_64.o    \
	compress42_thread_2_64.o                     \
	compress42_thread_3_64.o                     \
	compress42_thread_4_64.o                     \
	compress42_thread_5_64.o                     \
	compress42_thread_6_64.o                     \
	compress42_thread_7_64.o                     \
	stdio_v2_64arp.o compress42_64.o
	
	x86_64-w64-mingw32-gcc.exe -O3 -o            \
	BE_compress2_aakp_64.DLL -mdll               \
	arp.def                                      \
	amandaricardo_koci_dprintf_64arp.o           \
	arp_dll_64arp.o compress2_z_64.o             \
	compress2_2_z_64.o compress2dll_64.o         \
	longfile_64arp.o compress42_thread_1_64.o    \
	compress42_thread_2_64.o                     \
	compress42_thread_3_64.o                     \
	compress42_thread_4_64.o                     \
	compress42_thread_5_64.o                     \
	compress42_thread_6_64.o                     \
	compress42_thread_7_64.o                     \
	stdio_v2_64arp.o compress42_64.o             \
	-Wl,-enable-stdcall-fixup

	@cp BE_compress2_aakp_64.DLL ../../
	@cp BE_compress2_aakp_64.DLL  'C:\Amanda Ava Pereira\nosso_trabalho\amanda_projects\Lurdes_tar_gzip_parolin_k\files_k\tar_sample_ar_x64\tar_sample_ar\bin\Release'

	@./espaco_arp.exe 83
	

compress42_64.o :                                \
	c/tools/compress42.c
	x86_64-w64-mingw32-gcc.exe -c -o             \
	compress42_64.o                              \
	c/tools/compress42.c                         \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83
	
compress42_thread_1_64.o :                       \
	c/tools/compress42_thread_1.c
	x86_64-w64-mingw32-gcc.exe -c -o             \
	compress42_thread_1_64.o                     \
	c/tools/compress42_thread_1.c                \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83
	
compress42_thread_2_64.o :                       \
	c/tools/compress42_thread_2.c
	x86_64-w64-mingw32-gcc.exe -c -o             \
	compress42_thread_2_64.o                     \
	c/tools/compress42_thread_2.c                \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83
	
compress42_thread_3_64.o :                       \
	c/tools/compress42_thread_3.c
	x86_64-w64-mingw32-gcc.exe -c -o             \
	compress42_thread_3_64.o                     \
	c/tools/compress42_thread_3.c                \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83
	
compress42_thread_4_64.o :                       \
	c/tools/compress42_thread_4.c
	x86_64-w64-mingw32-gcc.exe -c -o             \
	compress42_thread_4_64.o                     \
	c/tools/compress42_thread_4.c                \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83
	
compress42_thread_5_64.o :                       \
	c/tools/compress42_thread_5.c
	x86_64-w64-mingw32-gcc.exe -c -o             \
	compress42_thread_5_64.o                     \
	c/tools/compress42_thread_5.c                \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83
	
compress42_thread_6_64.o :                       \
	c/tools/compress42_thread_6.c
	x86_64-w64-mingw32-gcc.exe -c -o             \
	compress42_thread_6_64.o                     \
	c/tools/compress42_thread_6.c                \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83
	
compress42_thread_7_64.o :                       \
	c/tools/compress42_thread_7.c
	x86_64-w64-mingw32-gcc.exe -c -o             \
	compress42_thread_7_64.o                     \
	c/tools/compress42_thread_7.c                \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83
	
longfile_64arp.o :                               \
	c/tools/longfile.c
	x86_64-w64-mingw32-gcc.exe -c -o             \
	longfile_64arp.o                             \
	c/tools/longfile.c                           \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83
	
stdio_v2_64arp.o :                               \
	c/tools/stdio_v2.c                           \
	c/tools/stdio_v2.h c/tools/stdio_v3.h
	x86_64-w64-mingw32-gcc.exe -c -o             \
	stdio_v2_64arp.o                             \
	c/tools/stdio_v2.c                           \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83
	
amandaricardo_koci_dprintf_64arp.o :             \
	c/tools/amandaricardo_koci_dprintf.c
	x86_64-w64-mingw32-gcc.exe -c -o             \
	amandaricardo_koci_dprintf_64arp.o           \
	c/tools/amandaricardo_koci_dprintf.c         \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83
	
arp_dll_64arp.o :                                \
	c/tools/helper_utilities_by_amanda_and_ricardo.c \
	c/tools/arp_dll.c c/tools/stdio_v2.h         \
	c/tools/stdio_v3.h
	x86_64-w64-mingw32-gcc.exe -c -o             \
	arp_dll_64arp.o c/tools/arp_dll.c            \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83
	
compress2_z_64.o :   c/tools/compress2_z.c       \
	c/tools/stdio_v2.h  c/tools/stdio_v3.h
	x86_64-w64-mingw32-gcc.exe -c -o             \
	compress2_z_64.o c/tools/compress2_z.c       \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83
#	unc77.bat c/tools/brotli.c

compress2_2_z_64.o :   c/tools/compress2_2_z.c
	x86_64-w64-mingw32-gcc.exe -c -o             \
	compress2_2_z_64.o c/tools/compress2_2_z.c   \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83

compress2dll_64.o :   c/tools/compress2dll.c
	x86_64-w64-mingw32-gcc.exe -c -o             \
	compress2dll_64.o c/tools/compress2dll.c     \
	$(AMANDA_FLAGS__) $(JULIET_FLAGS)            \
	$(FELINE_FLAGS__)
	@./espaco_arp.exe 83
	
clean_ar:
	-rm *.o