#2021 amanda & MathMan

AMANDA_FLAGS__=-O3 -Wextra -Wall -Wfatal-errors -Werror -Wextra -Wno-unused-function -Wno-stringop-truncation -DALE__

amanda_32: /bw_tmp/rsp_encrypt/koci_e_pereira_empreendimentos_encrypt_multi_thread_32.o /bw_tmp/rsp_encrypt/adlercheck_32.o /bw_tmp/rsp_encrypt/aes_32.o /bw_tmp/rsp_encrypt/pedro_32.o /bw_tmp/rsp_encrypt/cpu_32.o /bw_tmp/rsp_encrypt/crc32_32.o /bw_tmp/rsp_encrypt/dll_32.o /bw_tmp/rsp_encrypt/folder_i_32.o /bw_tmp/rsp_encrypt/hexa_32.o /bw_tmp/rsp_encrypt/longfile_32.o /bw_tmp/rsp_encrypt/rc4_32.o /bw_tmp/rsp_encrypt/sha512_k_32.o /bw_tmp/rsp_encrypt/serpent_32.o /bw_tmp/rsp_encrypt/mars_32.o /bw_tmp/rsp_encrypt/rc6_32.o /bw_tmp/rsp_encrypt/twofish_32.o /bw_tmp/rsp_encrypt/dprintf_32.o

#	-rm *.DLL *.dll *.ric *~ *.exe *.EXE *.o *.a

	@/bw_tmp/amandaricardo_mvbuild26_33.exe amanda_file_counter_32.ini versio_n.ama.rc version_ricardo_mislaine_final_2_.rc aline_definitive_header_2_.h "32 bits" RSP_encrypt_32.DLL increase

	@i686-w64-mingw32-windres.exe -o /bw_tmp/rsp_encrypt/amanda_ver32.o -O coff version_ricardo_mislaine_final_2_.rc

	i686-w64-mingw32-gcc.exe -mdll -O3 -o /bin/tar/x86/RSP_encrypt_32.DLL /bw_tmp/rsp_encrypt/amanda_ver32.o /bw_tmp/rsp_encrypt/koci_e_pereira_empreendimentos_encrypt_multi_thread_32.o /bw_tmp/rsp_encrypt/adlercheck_32.o /bw_tmp/rsp_encrypt/aes_32.o /bw_tmp/rsp_encrypt/pedro_32.o /bw_tmp/rsp_encrypt/cpu_32.o /bw_tmp/rsp_encrypt/crc32_32.o /bw_tmp/rsp_encrypt/dll_32.o /bw_tmp/rsp_encrypt/folder_i_32.o /bw_tmp/rsp_encrypt/hexa_32.o /bw_tmp/rsp_encrypt/longfile_32.o /bw_tmp/rsp_encrypt/rc4_32.o /bw_tmp/rsp_encrypt/sha512_k_32.o /bw_tmp/rsp_encrypt/serpent_32.o /bw_tmp/rsp_encrypt/mars_32.o /bw_tmp/rsp_encrypt/rc6_32.o /bw_tmp/rsp_encrypt/twofish_32.o /bw_tmp/rsp_encrypt/dprintf_32.o controlname_k.c -Wl,-enable-stdcall-fixup dll_k.def

/bw_tmp/rsp_encrypt/koci_e_pereira_empreendimentos_encrypt_multi_thread_32.o : koci_e_pereira_empreendimentos_encrypt_multi_thread.c the_thread_function_p.c include_multi_k__p.h
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/rsp_encrypt/koci_e_pereira_empreendimentos_encrypt_multi_thread_32.o koci_e_pereira_empreendimentos_encrypt_multi_thread.c $(AMANDA_FLAGS__)

/bw_tmp/rsp_encrypt/pedro_32.o: pedro.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/rsp_encrypt/pedro_32.o pedro.c $(AMANDA_FLAGS__)

/bw_tmp/rsp_encrypt/sha512_k_32.o: sha512_file_k.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/rsp_encrypt/sha512_k_32.o sha512_file_k.c $(AMANDA_FLAGS__)
	
/bw_tmp/rsp_encrypt/mars_32.o: mars.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/rsp_encrypt/mars_32.o mars.c $(AMANDA_FLAGS__)

/bw_tmp/rsp_encrypt/rc6_32.o: rc6.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/rsp_encrypt/rc6_32.o rc6.c $(AMANDA_FLAGS__)

/bw_tmp/rsp_encrypt/twofish_32.o: twofish.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/rsp_encrypt/twofish_32.o twofish.c $(AMANDA_FLAGS__)

/bw_tmp/rsp_encrypt/serpent_32.o: serpent.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/rsp_encrypt/serpent_32.o serpent.c $(AMANDA_FLAGS__)

/bw_tmp/rsp_encrypt/adlercheck_32.o: adlercheck.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/rsp_encrypt/adlercheck_32.o adlercheck.c $(AMANDA_FLAGS__)

/bw_tmp/rsp_encrypt/aes_32.o: aes.c aes.h
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/rsp_encrypt/aes_32.o aes.c $(AMANDA_FLAGS__)

/bw_tmp/rsp_encrypt/amandaricardo_koci_dprintf_32.o:  amandaricardo_koci_dprintf.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/rsp_encrypt/amandaricardo_koci_dprintf_32.o amandaricardo_koci_dprintf.c $(AMANDA_FLAGS__)
	
/bw_tmp/rsp_encrypt/cpu_32.o: cpu.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/rsp_encrypt/cpu_32.o cpu.c $(AMANDA_FLAGS__)
	
/bw_tmp/rsp_encrypt/crc32_32.o: crc32.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/rsp_encrypt/crc32_32.o crc32.c $(AMANDA_FLAGS__)
	
/bw_tmp/rsp_encrypt/dll_32.o: dll.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/rsp_encrypt/dll_32.o dll.c $(AMANDA_FLAGS__)

/bw_tmp/rsp_encrypt/dprintf_32.o: dprintf.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/rsp_encrypt/dprintf_32.o dprintf.c $(AMANDA_FLAGS__)

/bw_tmp/rsp_encrypt/folder_i_32.o: folder.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/rsp_encrypt/folder_i_32.o folder.c $(AMANDA_FLAGS__)
	
/bw_tmp/rsp_encrypt/hexa_32.o: hexa.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/rsp_encrypt/hexa_32.o hexa.c $(AMANDA_FLAGS__)
	
/bw_tmp/rsp_encrypt/longfile_32.o: longfile.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/rsp_encrypt/longfile_32.o longfile.c $(AMANDA_FLAGS__)
	
/bw_tmp/rsp_encrypt/rc4_32.o: rc4.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/rsp_encrypt/rc4_32.o rc4.c $(AMANDA_FLAGS__)
		
#####################################################64 bits, for your pleasure...###############################################################################
ricardo_64:	/bw_tmp/rsp_encrypt/koci_e_pereira_empreendimentos_encrypt_multi_thread_64.o /bw_tmp/rsp_encrypt/adlercheck_64.o /bw_tmp/rsp_encrypt/aes_64.o /bw_tmp/rsp_encrypt/pedro_64.o /bw_tmp/rsp_encrypt/cpu_64.o /bw_tmp/rsp_encrypt/crc32_64.o /bw_tmp/rsp_encrypt/dll_64.o /bw_tmp/rsp_encrypt/dprintf_64.o /bw_tmp/rsp_encrypt/folder_64.o /bw_tmp/rsp_encrypt/hexa_64.o /bw_tmp/rsp_encrypt/longfile_64.o /bw_tmp/rsp_encrypt/rc4_64.o /bw_tmp/rsp_encrypt/sha512_k_64.o /bw_tmp/rsp_encrypt/serpent_64.o /bw_tmp/rsp_encrypt/mars_64.o /bw_tmp/rsp_encrypt/rc6_64.o /bw_tmp/rsp_encrypt/twofish_64.o

	@/bw_tmp/amandaricardo_mvbuild26_33.exe amanda_file_counter_32.ini versio_n.ama.rc version_ricardo_mislaine_final_2_.rc aline_definitive_header_2_.h "64 bits" RSP_encrypt_64.DLL increase

	@x86_64-w64-mingw32-windres.exe -o /bw_tmp/rsp_encrypt/amanda_ver64.o -O coff version_ricardo_mislaine_final_2_.rc

	x86_64-w64-mingw32-gcc -mdll -O3 -o /bin/tar/x64/RSP_encrypt_64.DLL /bw_tmp/rsp_encrypt/amanda_ver64.o /bw_tmp/rsp_encrypt/koci_e_pereira_empreendimentos_encrypt_multi_thread_64.o /bw_tmp/rsp_encrypt/adlercheck_64.o /bw_tmp/rsp_encrypt/aes_64.o /bw_tmp/rsp_encrypt/pedro_64.o /bw_tmp/rsp_encrypt/cpu_64.o /bw_tmp/rsp_encrypt/crc32_64.o /bw_tmp/rsp_encrypt/dll_64.o /bw_tmp/rsp_encrypt/dprintf_64.o /bw_tmp/rsp_encrypt/folder_64.o /bw_tmp/rsp_encrypt/hexa_64.o /bw_tmp/rsp_encrypt/longfile_64.o /bw_tmp/rsp_encrypt/rc4_64.o /bw_tmp/rsp_encrypt/sha512_k_64.o /bw_tmp/rsp_encrypt/serpent_64.o /bw_tmp/rsp_encrypt/mars_64.o /bw_tmp/rsp_encrypt/rc6_64.o /bw_tmp/rsp_encrypt/twofish_64.o controlname_k.c -Wl,-enable-stdcall-fixup dll_k.def
		

/bw_tmp/rsp_encrypt/koci_e_pereira_empreendimentos_encrypt_multi_thread_64.o : koci_e_pereira_empreendimentos_encrypt_multi_thread.c the_thread_function_p.c include_multi_k__p.h
	x86_64-w64-mingw32-gcc -c -o /bw_tmp/rsp_encrypt/koci_e_pereira_empreendimentos_encrypt_multi_thread_64.o koci_e_pereira_empreendimentos_encrypt_multi_thread.c $(AMANDA_FLAGS__)

/bw_tmp/rsp_encrypt/sha512_k_64.o: sha512_file_k.c
	x86_64-w64-mingw32-gcc -c -o /bw_tmp/rsp_encrypt/sha512_k_64.o sha512_file_k.c $(AMANDA_FLAGS__)
	
/bw_tmp/rsp_encrypt/adlercheck_64.o: adlercheck.c
	x86_64-w64-mingw32-gcc -c -o /bw_tmp/rsp_encrypt/adlercheck_64.o adlercheck.c $(AMANDA_FLAGS__)
	
/bw_tmp/rsp_encrypt/twofish_64.o: twofish.c
	x86_64-w64-mingw32-gcc -c -o /bw_tmp/rsp_encrypt/twofish_64.o twofish.c $(AMANDA_FLAGS__)
	
/bw_tmp/rsp_encrypt/serpent_64.o: serpent.c
	x86_64-w64-mingw32-gcc -c -o /bw_tmp/rsp_encrypt/serpent_64.o serpent.c $(AMANDA_FLAGS__)
	
/bw_tmp/rsp_encrypt/mars_64.o: mars.c
	x86_64-w64-mingw32-gcc -c -o /bw_tmp/rsp_encrypt/mars_64.o mars.c $(AMANDA_FLAGS__)
	
/bw_tmp/rsp_encrypt/rc6_64.o: rc6.c
	x86_64-w64-mingw32-gcc -c -o /bw_tmp/rsp_encrypt/rc6_64.o rc6.c $(AMANDA_FLAGS__)
	
/bw_tmp/rsp_encrypt/aes_64.o: aes.c aes.h
	x86_64-w64-mingw32-gcc -c -o /bw_tmp/rsp_encrypt/aes_64.o aes.c $(AMANDA_FLAGS__)
	
/bw_tmp/rsp_encrypt/pedro_64.o: pedro.c
	x86_64-w64-mingw32-gcc -c -o /bw_tmp/rsp_encrypt/pedro_64.o pedro.c $(AMANDA_FLAGS__)
	
/bw_tmp/rsp_encrypt/cpu_64.o: cpu.c
	x86_64-w64-mingw32-gcc -c -o /bw_tmp/rsp_encrypt/cpu_64.o cpu.c $(AMANDA_FLAGS__)
	
/bw_tmp/rsp_encrypt/crc32_64.o: crc32.c
	x86_64-w64-mingw32-gcc -c -o /bw_tmp/rsp_encrypt/crc32_64.o crc32.c $(AMANDA_FLAGS__)
	
/bw_tmp/rsp_encrypt/dll_64.o: dll.c
	x86_64-w64-mingw32-gcc -c -o /bw_tmp/rsp_encrypt/dll_64.o dll.c $(AMANDA_FLAGS__)
	
/bw_tmp/rsp_encrypt/dprintf_64.o: dprintf.c
	x86_64-w64-mingw32-gcc -c -o /bw_tmp/rsp_encrypt/dprintf_64.o dprintf.c $(AMANDA_FLAGS__)
	
/bw_tmp/rsp_encrypt/folder_64.o: folder.c
	x86_64-w64-mingw32-gcc -c -o /bw_tmp/rsp_encrypt/folder_64.o folder.c $(AMANDA_FLAGS__)
	
/bw_tmp/rsp_encrypt/hexa_64.o: hexa.c
	x86_64-w64-mingw32-gcc -c -o /bw_tmp/rsp_encrypt/hexa_64.o hexa.c $(AMANDA_FLAGS__)
	
/bw_tmp/rsp_encrypt/longfile_64.o: longfile.c
	x86_64-w64-mingw32-gcc -c -o /bw_tmp/rsp_encrypt/longfile_64.o longfile.c $(AMANDA_FLAGS__)
	
/bw_tmp/rsp_encrypt/rc4_64.o: rc4.c
	x86_64-w64-mingw32-gcc -c -o /bw_tmp/rsp_encrypt/rc4_64.o rc4.c $(AMANDA_FLAGS__)