#hi, are you having a great day like us? , notice that in order to compile it you need cygwin 3.1.7 or above with mingw64 toolchain and mingw...

#version of the compilers, for win64 11.1.0 and for win32 also 11.1.0

AMANDA_FLAGS__=-O3 -Wall -Wfatal-errors -Werror -Wno-unused-function

amanda_win32: /bw_tmp/gzip/adler32_32.o /bw_tmp/gzip/compress_32.o /bw_tmp/gzip/crc32_32.o /bw_tmp/gzip/deflate_32.o /bw_tmp/gzip/gzclose_32.o /bw_tmp/gzip/gzlib_32.o /bw_tmp/gzip/gzread_32.o /bw_tmp/gzip/gzwrite_32.o /bw_tmp/gzip/infback_32.o /bw_tmp/gzip/inffast_32.o /bw_tmp/gzip/inflate_32.o /bw_tmp/gzip/inftrees_32.o /bw_tmp/gzip/trees_32.o /bw_tmp/gzip/uncompr_32.o /bw_tmp/gzip/zutil_32.o

#	-rm *.DLL *.dll *.ric *~ *.exe *.EXE *.o *.a

	@i686-w64-mingw32-ar rcs /bw_tmp/gzip/ricardo_zlib32.a /bw_tmp/gzip/adler32_32.o /bw_tmp/gzip/compress_32.o /bw_tmp/gzip/crc32_32.o /bw_tmp/gzip/deflate_32.o /bw_tmp/gzip/gzclose_32.o /bw_tmp/gzip/gzlib_32.o /bw_tmp/gzip/gzread_32.o /bw_tmp/gzip/gzwrite_32.o /bw_tmp/gzip/infback_32.o /bw_tmp/gzip/inffast_32.o /bw_tmp/gzip/inflate_32.o /bw_tmp/gzip/inftrees_32.o /bw_tmp/gzip/trees_32.o /bw_tmp/gzip/uncompr_32.o /bw_tmp/gzip/zutil_32.o

/bw_tmp/gzip/adler32_32.o: adler32.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/adler32_32.o adler32.c $(AMANDA_FLAGS__)

/bw_tmp/gzip/compress_32.o: compress.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/compress_32.o compress.c $(AMANDA_FLAGS__)

/bw_tmp/gzip/crc32_32.o: crc32.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/crc32_32.o crc32.c $(AMANDA_FLAGS__)

/bw_tmp/gzip/deflate_32.o: deflate.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/deflate_32.o deflate.c $(AMANDA_FLAGS__)

/bw_tmp/gzip/gzclose_32.o: gzclose.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/gzclose_32.o gzclose.c $(AMANDA_FLAGS__)

/bw_tmp/gzip/gzlib_32.o: gzlib.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/gzlib_32.o gzlib.c $(AMANDA_FLAGS__)

/bw_tmp/gzip/gzread_32.o: gzread.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/gzread_32.o gzread.c $(AMANDA_FLAGS__)

/bw_tmp/gzip/gzwrite_32.o: gzwrite.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/gzwrite_32.o gzwrite.c $(AMANDA_FLAGS__)

/bw_tmp/gzip/infback_32.o: infback.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/infback_32.o infback.c $(AMANDA_FLAGS__)

/bw_tmp/gzip/inffast_32.o: inffast.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/inffast_32.o inffast.c $(AMANDA_FLAGS__)

/bw_tmp/gzip/inflate_32.o: inflate.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/inflate_32.o inflate.c $(AMANDA_FLAGS__)

/bw_tmp/gzip/inftrees_32.o: inftrees.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/inftrees_32.o inftrees.c $(AMANDA_FLAGS__)

/bw_tmp/gzip/trees_32.o: trees.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/trees_32.o trees.c $(AMANDA_FLAGS__)

/bw_tmp/gzip/uncompr_32.o: uncompr.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/uncompr_32.o uncompr.c $(AMANDA_FLAGS__)

/bw_tmp/gzip/zutil_32.o: zutil.c
	i686-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/zutil_32.o zutil.c $(AMANDA_FLAGS__)

ricardo_win64: /bw_tmp/gzip/adler32_64.o /bw_tmp/gzip/compress_64.o /bw_tmp/gzip/crc32_64.o /bw_tmp/gzip/deflate_64.o /bw_tmp/gzip/gzclose_64.o /bw_tmp/gzip/gzlib_64.o /bw_tmp/gzip/gzread_64.o /bw_tmp/gzip/gzwrite_64.o /bw_tmp/gzip/infback_64.o /bw_tmp/gzip/inffast_64.o /bw_tmp/gzip/inflate_64.o /bw_tmp/gzip/inftrees_64.o /bw_tmp/gzip/trees_64.o /bw_tmp/gzip/uncompr_64.o /bw_tmp/gzip/zutil_64.o

	@x86_64-w64-mingw32-ar rcs /bw_tmp/gzip/amanda_zlib64.a /bw_tmp/gzip/adler32_64.o /bw_tmp/gzip/compress_64.o /bw_tmp/gzip/crc32_64.o /bw_tmp/gzip/deflate_64.o /bw_tmp/gzip/gzclose_64.o /bw_tmp/gzip/gzlib_64.o /bw_tmp/gzip/gzread_64.o /bw_tmp/gzip/gzwrite_64.o /bw_tmp/gzip/infback_64.o /bw_tmp/gzip/inffast_64.o /bw_tmp/gzip/inflate_64.o /bw_tmp/gzip/inftrees_64.o /bw_tmp/gzip/trees_64.o /bw_tmp/gzip/uncompr_64.o /bw_tmp/gzip/zutil_64.o

/bw_tmp/gzip/adler32_64.o: adler32.c
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/adler32_64.o adler32.c $(AMANDA_FLAGS__)

/bw_tmp/gzip/compress_64.o: compress.c
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/compress_64.o compress.c $(AMANDA_FLAGS__)

/bw_tmp/gzip/crc32_64.o: crc32.c
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/crc32_64.o crc32.c $(AMANDA_FLAGS__)

/bw_tmp/gzip/deflate_64.o: deflate.c
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/deflate_64.o deflate.c $(AMANDA_FLAGS__)

/bw_tmp/gzip/gzclose_64.o: gzclose.c
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/gzclose_64.o gzclose.c $(AMANDA_FLAGS__)

/bw_tmp/gzip/gzlib_64.o: gzlib.c
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/gzlib_64.o gzlib.c $(AMANDA_FLAGS__)

/bw_tmp/gzip/gzread_64.o: gzread.c
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/gzread_64.o gzread.c $(AMANDA_FLAGS__)

/bw_tmp/gzip/gzwrite_64.o: gzwrite.c
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/gzwrite_64.o gzwrite.c $(AMANDA_FLAGS__)

/bw_tmp/gzip/infback_64.o: infback.c
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/infback_64.o infback.c $(AMANDA_FLAGS__)

/bw_tmp/gzip/inffast_64.o: inffast.c
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/inffast_64.o inffast.c $(AMANDA_FLAGS__)

/bw_tmp/gzip/inflate_64.o: inflate.c
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/inflate_64.o inflate.c $(AMANDA_FLAGS__)

/bw_tmp/gzip/inftrees_64.o: inftrees.c
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/inftrees_64.o inftrees.c $(AMANDA_FLAGS__)

/bw_tmp/gzip/trees_64.o: trees.c
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/trees_64.o trees.c $(AMANDA_FLAGS__)

/bw_tmp/gzip/uncompr_64.o: uncompr.c
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/uncompr_64.o uncompr.c $(AMANDA_FLAGS__)

/bw_tmp/gzip/zutil_64.o: zutil.c
	x86_64-w64-mingw32-gcc.exe -c -o /bw_tmp/gzip/zutil_64.o zutil.c $(AMANDA_FLAGS__)
