#2021 amanda and MathMan

amanda_32:
	-mkdir 'C:/Amanda Ava Pereira/nosso_trabalho/amanda_projects/Lurdes_tar_gzip_parolin_k/files_k/tar_1_33_k/libarchive_source_code'
	cp -r --preserve=timestamps * 'C:/Amanda Ava Pereira/nosso_trabalho/amanda_projects/Lurdes_tar_gzip_parolin_k/files_k/tar_1_33_k/libarchive_source_code'
